/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as TenantRouteImport } from './routes/$tenant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/$tenant.index'
import { Route as TenantSobreRouteImport } from './routes/$tenant.sobre'
import { Route as TenantPoliticaDePrivacidadeRouteImport } from './routes/$tenant.politica-de-privacidade'
import { Route as TenantLigamosParaVoceRouteImport } from './routes/$tenant.ligamos-para-voce'
import { Route as TenantLancamentosRouteImport } from './routes/$tenant.lancamentos'
import { Route as TenantFavoritosRouteImport } from './routes/$tenant.favoritos'
import { Route as TenantContatoRouteImport } from './routes/$tenant.contato'
import { Route as TenantBuscarRouteImport } from './routes/$tenant.buscar'
import { Route as TenantAvaliarRouteImport } from './routes/$tenant.avaliar'
import { Route as TenantAnunciarRouteImport } from './routes/$tenant.anunciar'
import { Route as TenantBlogIndexRouteImport } from './routes/$tenant.blog.index'
import { Route as TenantImovelIdRouteImport } from './routes/$tenant.imovel.$id'
import { Route as TenantBlogSlugRouteImport } from './routes/$tenant.blog.$slug'

const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const TenantSobreRoute = TenantSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPoliticaDePrivacidadeRoute =
  TenantPoliticaDePrivacidadeRouteImport.update({
    id: '/politica-de-privacidade',
    path: '/politica-de-privacidade',
    getParentRoute: () => TenantRoute,
  } as any)
const TenantLigamosParaVoceRoute = TenantLigamosParaVoceRouteImport.update({
  id: '/ligamos-para-voce',
  path: '/ligamos-para-voce',
  getParentRoute: () => TenantRoute,
} as any)
const TenantLancamentosRoute = TenantLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => TenantRoute,
} as any)
const TenantFavoritosRoute = TenantFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => TenantRoute,
} as any)
const TenantContatoRoute = TenantContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBuscarRoute = TenantBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAvaliarRoute = TenantAvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAnunciarRoute = TenantAnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBlogIndexRoute = TenantBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => TenantRoute,
} as any)
const TenantImovelIdRoute = TenantImovelIdRouteImport.update({
  id: '/imovel/$id',
  path: '/imovel/$id',
  getParentRoute: () => TenantRoute,
} as any)
const TenantBlogSlugRoute = TenantBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => TenantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/builder': typeof BuilderRoute
  '/$tenant/anunciar': typeof TenantAnunciarRoute
  '/$tenant/avaliar': typeof TenantAvaliarRoute
  '/$tenant/buscar': typeof TenantBuscarRoute
  '/$tenant/contato': typeof TenantContatoRoute
  '/$tenant/favoritos': typeof TenantFavoritosRoute
  '/$tenant/lancamentos': typeof TenantLancamentosRoute
  '/$tenant/ligamos-para-voce': typeof TenantLigamosParaVoceRoute
  '/$tenant/politica-de-privacidade': typeof TenantPoliticaDePrivacidadeRoute
  '/$tenant/sobre': typeof TenantSobreRoute
  '/$tenant/': typeof TenantIndexRoute
  '/$tenant/blog/$slug': typeof TenantBlogSlugRoute
  '/$tenant/imovel/$id': typeof TenantImovelIdRoute
  '/$tenant/blog/': typeof TenantBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/$tenant/anunciar': typeof TenantAnunciarRoute
  '/$tenant/avaliar': typeof TenantAvaliarRoute
  '/$tenant/buscar': typeof TenantBuscarRoute
  '/$tenant/contato': typeof TenantContatoRoute
  '/$tenant/favoritos': typeof TenantFavoritosRoute
  '/$tenant/lancamentos': typeof TenantLancamentosRoute
  '/$tenant/ligamos-para-voce': typeof TenantLigamosParaVoceRoute
  '/$tenant/politica-de-privacidade': typeof TenantPoliticaDePrivacidadeRoute
  '/$tenant/sobre': typeof TenantSobreRoute
  '/$tenant': typeof TenantIndexRoute
  '/$tenant/blog/$slug': typeof TenantBlogSlugRoute
  '/$tenant/imovel/$id': typeof TenantImovelIdRoute
  '/$tenant/blog': typeof TenantBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenant': typeof TenantRouteWithChildren
  '/builder': typeof BuilderRoute
  '/$tenant/anunciar': typeof TenantAnunciarRoute
  '/$tenant/avaliar': typeof TenantAvaliarRoute
  '/$tenant/buscar': typeof TenantBuscarRoute
  '/$tenant/contato': typeof TenantContatoRoute
  '/$tenant/favoritos': typeof TenantFavoritosRoute
  '/$tenant/lancamentos': typeof TenantLancamentosRoute
  '/$tenant/ligamos-para-voce': typeof TenantLigamosParaVoceRoute
  '/$tenant/politica-de-privacidade': typeof TenantPoliticaDePrivacidadeRoute
  '/$tenant/sobre': typeof TenantSobreRoute
  '/$tenant/': typeof TenantIndexRoute
  '/$tenant/blog/$slug': typeof TenantBlogSlugRoute
  '/$tenant/imovel/$id': typeof TenantImovelIdRoute
  '/$tenant/blog/': typeof TenantBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenant'
    | '/builder'
    | '/$tenant/anunciar'
    | '/$tenant/avaliar'
    | '/$tenant/buscar'
    | '/$tenant/contato'
    | '/$tenant/favoritos'
    | '/$tenant/lancamentos'
    | '/$tenant/ligamos-para-voce'
    | '/$tenant/politica-de-privacidade'
    | '/$tenant/sobre'
    | '/$tenant/'
    | '/$tenant/blog/$slug'
    | '/$tenant/imovel/$id'
    | '/$tenant/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/$tenant/anunciar'
    | '/$tenant/avaliar'
    | '/$tenant/buscar'
    | '/$tenant/contato'
    | '/$tenant/favoritos'
    | '/$tenant/lancamentos'
    | '/$tenant/ligamos-para-voce'
    | '/$tenant/politica-de-privacidade'
    | '/$tenant/sobre'
    | '/$tenant'
    | '/$tenant/blog/$slug'
    | '/$tenant/imovel/$id'
    | '/$tenant/blog'
  id:
    | '__root__'
    | '/'
    | '/$tenant'
    | '/builder'
    | '/$tenant/anunciar'
    | '/$tenant/avaliar'
    | '/$tenant/buscar'
    | '/$tenant/contato'
    | '/$tenant/favoritos'
    | '/$tenant/lancamentos'
    | '/$tenant/ligamos-para-voce'
    | '/$tenant/politica-de-privacidade'
    | '/$tenant/sobre'
    | '/$tenant/'
    | '/$tenant/blog/$slug'
    | '/$tenant/imovel/$id'
    | '/$tenant/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantRoute: typeof TenantRouteWithChildren
  BuilderRoute: typeof BuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/': {
      id: '/$tenant/'
      path: '/'
      fullPath: '/$tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/sobre': {
      id: '/$tenant/sobre'
      path: '/sobre'
      fullPath: '/$tenant/sobre'
      preLoaderRoute: typeof TenantSobreRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/politica-de-privacidade': {
      id: '/$tenant/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/$tenant/politica-de-privacidade'
      preLoaderRoute: typeof TenantPoliticaDePrivacidadeRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/ligamos-para-voce': {
      id: '/$tenant/ligamos-para-voce'
      path: '/ligamos-para-voce'
      fullPath: '/$tenant/ligamos-para-voce'
      preLoaderRoute: typeof TenantLigamosParaVoceRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/lancamentos': {
      id: '/$tenant/lancamentos'
      path: '/lancamentos'
      fullPath: '/$tenant/lancamentos'
      preLoaderRoute: typeof TenantLancamentosRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/favoritos': {
      id: '/$tenant/favoritos'
      path: '/favoritos'
      fullPath: '/$tenant/favoritos'
      preLoaderRoute: typeof TenantFavoritosRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/contato': {
      id: '/$tenant/contato'
      path: '/contato'
      fullPath: '/$tenant/contato'
      preLoaderRoute: typeof TenantContatoRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/buscar': {
      id: '/$tenant/buscar'
      path: '/buscar'
      fullPath: '/$tenant/buscar'
      preLoaderRoute: typeof TenantBuscarRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/avaliar': {
      id: '/$tenant/avaliar'
      path: '/avaliar'
      fullPath: '/$tenant/avaliar'
      preLoaderRoute: typeof TenantAvaliarRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/anunciar': {
      id: '/$tenant/anunciar'
      path: '/anunciar'
      fullPath: '/$tenant/anunciar'
      preLoaderRoute: typeof TenantAnunciarRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/blog/': {
      id: '/$tenant/blog/'
      path: '/blog'
      fullPath: '/$tenant/blog/'
      preLoaderRoute: typeof TenantBlogIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/imovel/$id': {
      id: '/$tenant/imovel/$id'
      path: '/imovel/$id'
      fullPath: '/$tenant/imovel/$id'
      preLoaderRoute: typeof TenantImovelIdRouteImport
      parentRoute: typeof TenantRoute
    }
    '/$tenant/blog/$slug': {
      id: '/$tenant/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$tenant/blog/$slug'
      preLoaderRoute: typeof TenantBlogSlugRouteImport
      parentRoute: typeof TenantRoute
    }
  }
}

interface TenantRouteChildren {
  TenantAnunciarRoute: typeof TenantAnunciarRoute
  TenantAvaliarRoute: typeof TenantAvaliarRoute
  TenantBuscarRoute: typeof TenantBuscarRoute
  TenantContatoRoute: typeof TenantContatoRoute
  TenantFavoritosRoute: typeof TenantFavoritosRoute
  TenantLancamentosRoute: typeof TenantLancamentosRoute
  TenantLigamosParaVoceRoute: typeof TenantLigamosParaVoceRoute
  TenantPoliticaDePrivacidadeRoute: typeof TenantPoliticaDePrivacidadeRoute
  TenantSobreRoute: typeof TenantSobreRoute
  TenantIndexRoute: typeof TenantIndexRoute
  TenantBlogSlugRoute: typeof TenantBlogSlugRoute
  TenantImovelIdRoute: typeof TenantImovelIdRoute
  TenantBlogIndexRoute: typeof TenantBlogIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantAnunciarRoute: TenantAnunciarRoute,
  TenantAvaliarRoute: TenantAvaliarRoute,
  TenantBuscarRoute: TenantBuscarRoute,
  TenantContatoRoute: TenantContatoRoute,
  TenantFavoritosRoute: TenantFavoritosRoute,
  TenantLancamentosRoute: TenantLancamentosRoute,
  TenantLigamosParaVoceRoute: TenantLigamosParaVoceRoute,
  TenantPoliticaDePrivacidadeRoute: TenantPoliticaDePrivacidadeRoute,
  TenantSobreRoute: TenantSobreRoute,
  TenantIndexRoute: TenantIndexRoute,
  TenantBlogSlugRoute: TenantBlogSlugRoute,
  TenantImovelIdRoute: TenantImovelIdRoute,
  TenantBlogIndexRoute: TenantBlogIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantRoute: TenantRouteWithChildren,
  BuilderRoute: BuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
